# Generated by Django 2.2.4 on 2021-09-03 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import podomarket.validators


class Migration(migrations.Migration):

    dependencies = [
        ('podomarket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.CharField(max_length=2, null=True, validators=[podomarket.validators.include_rank]),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True)),
                ('dt_updated', models.DateTimeField(auto_now=True)),
                ('platoon_member', models.CharField(max_length=10)),
                ('testing_pic', models.ImageField(blank=True, upload_to='item_pics')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
