# Generated by Django 2.2.4 on 2021-08-15 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podomarket', '0002_auto_20210815_0122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='adress',
            new_name='address',
        ),
    ]
