# Generated by Django 2.2.4 on 2021-09-04 04:13

from django.db import migrations, models
import podomarket.validators


class Migration(migrations.Migration):

    dependencies = [
        ('podomarket', '0003_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='platoon_member_rank',
            field=models.CharField(max_length=2, null=True, validators=[podomarket.validators.include_rank]),
        ),
    ]
