# Generated by Django 2.2.4 on 2021-09-04 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podomarket', '0004_post_platoon_member_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='testing_pic',
        ),
    ]
